services:

  web:
    build:
        context: ./services/web
        dockerfile: Dockerfile
        target: prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static/
      - template_volume:/home/app/web/project/templates/
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static/
    ports:
      - 443:80
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  postgres_data_prod:
  static_volume:
