services:
  web:
    build:
      context: ./web
    command: gunicorn 'web:app' --bind 0.0.0.0:5000 --workers 3
    ports:
      - "5000:5000"
    volumes:
    - .:/home/app/web
    env_file:
    - ./.env
    depends_on:
    - nginx
    networks:
    - app_network


  nginx:
    build: 
      context: ./nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
    - app_network

networks:
  app_network:
    driver: bridge
