services:
  web:
    build:
      context: ./web
    command: gunicorn 'web:app' --bind 0.0.0.0:5000 --workers 3
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
    - .:/home/app/web
    env_file:
    - ./.env
    networks:
    - app_network
    restart: always

networks:
  app_network:
    driver: bridge